# Generated by Django 4.0.1 on 2022-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('count', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
