# Generated by Django 4.0.1 on 2022-01-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='count',
        ),
    ]
